/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./assets/invest20.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/invest20.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['20Invest'].geometry} material={materials['Material.001']} position={[-0.212, -0.012, -0.267]} scale={[-7.014, -0.734, -7.014]} />
    </group>
  )
}

useGLTF.preload('/invest20.gltf')
