/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./assets/save50.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/save50.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['50percent'].geometry} material={materials.Save} scale={[7.34, 0.734, 7.34]} />
    </group>
  )
}

useGLTF.preload('/save50.gltf')
