/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./assets/save50.gltf -t 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['50save']: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/save50.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['50save'].geometry} material={materials['Material.001']} position={[-0.007, 0, -0.43]} scale={[1.969, 0.132, 1.969]} />
    </group>
  )
}

useGLTF.preload('/save50.gltf')
