/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./assets/save50.gltf -t 
*/

import * as THREE from 'three'
import React, { useRef,forwardRef } from 'react'
import { GLTF } from 'three-stdlib'



export const Lighting = (props:any) => {
  
  return (
    <group>
        <pointLight intensity={1} color="cc00cc" position={[-10, 10, 2]} /> 

        <pointLight intensity={1}  color="cc00cc" position={[10, -10, 2]} /> 
    </group>

  )
}
