/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./assets/save50.gltf -t 
*/

import * as THREE from 'three'
import React, { useRef,forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['50save']: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

export const Save50 = forwardRef(function Save50(props: JSX.IntrinsicElements['group'], ref) {
  const { nodes, materials } = useGLTF('/save50.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['50save'].geometry} material={materials['Material.001']} position={[-0.007, 0, -0.43]} scale={[5.2, 0.132, 5.2]} />
    </group>
  )
})

useGLTF.preload('/save50.gltf')
